### ISSUE TITLE
icons are breaking

### ISSUE THREAD

**Issue by sandor** [jarek-foksa/xel#25] opened 2017-05-24 10:23 UTC
using this will show the icons as intended (see first screenshot):
```
					<div class="Grid-cell Grid--full">
						<div class="content">
							<x-buttons style="padding:4px;" tracking="1">
								<x-button skin="plain">
									<x-icon name="edit"></x-icon>
									<x-label style="margin-left:4px;">Editor</x-label>
								</x-button>

								<x-button skin="plain">
									<x-icon name="visibility"></x-icon>
									<x-label style="margin-left:4px;">Preview</x-label>
								</x-button>

								<x-button skin="plain">
									<x-icon name="code"></x-icon>
									<x-label style="margin-left:4px;">Code</x-label>
								</x-button>
							</x-buttons>
						</div>
					</div>
					<div class="Grid-cell right-menu">
						<div class="content">
							<x-buttons tracking="1">
								<x-button skin="iconic">
									<x-box vertical>
										<x-icon name="extensions-color"></x-icon>
										<x-label>Editor</x-label>
									</x-box>
								</x-button>

								<x-button skin="iconic">
									<x-box vertical>
										<x-icon name="visibility"></x-icon>
										<x-label>Preview</x-label>
									</x-box>
								</x-button>

							</x-buttons>
						</div>
					</div>
```
changing the icon name (extension-color) to edit will break the icons (screenshot2):

```
					<div class="Grid-cell Grid--full">
						<div class="content">
							<x-buttons style="padding:4px;" tracking="1">
								<x-button skin="plain">
									<x-icon name="edit"></x-icon>
									<x-label style="margin-left:4px;">Editor</x-label>
								</x-button>

								<x-button skin="plain">
									<x-icon name="visibility"></x-icon>
									<x-label style="margin-left:4px;">Preview</x-label>
								</x-button>

								<x-button skin="plain">
									<x-icon name="code"></x-icon>
									<x-label style="margin-left:4px;">Code</x-label>
								</x-button>
							</x-buttons>
						</div>
					</div>
					<div class="Grid-cell right-menu">
						<div class="content">
							<x-buttons tracking="1">
								<x-button skin="iconic">
									<x-box vertical>
										<x-icon name="edit"></x-icon>
										<x-label>Editor</x-label>
									</x-box>
								</x-button>

								<x-button skin="iconic">
									<x-box vertical>
										<x-icon name="visibility"></x-icon>
										<x-label>Preview</x-label>
									</x-box>
								</x-button>

							</x-buttons>
						</div>
					</div>
```
![1](https://cloud.githubusercontent.com/assets/476224/26399016/b40606e0-407b-11e7-836d-964439880562.jpg)
![2](https://cloud.githubusercontent.com/assets/476224/26399028/bd2ea47a-407b-11e7-8a78-cdd0c6062f41.jpg)

**Comment by jarek-foksa** [comment] 2017-05-24 11:58
Can you reproduce this issue with Electron 1.7.x? I suspect this is caused by [Chrome bug 597080 ](https://bugs.chromium.org/p/chromium/issues/detail?id=597080#c12).

**Comment by sandor** [comment] 2017-05-24 12:16
sorry for my ignorance jarek – I am using the prebuilt version 1.6.8 (I think last stable?) and I don't know how to update to 1.7.x ... (a quick tip here for a newbie?) But anyhow this seems to be the problem. If I build a new iconset like the one you are using (the boxy-svg stuff) and I use ONLY those icons than the icons seems to work well...

**Comment by sandor** [comment] 2017-05-24 12:52
hmmm... made some further testing. I suppose that there is somehow a conflict if we use the "Iconic" skin and other icons than the your icons from icons.svg...

**Comment by jarek-foksa** [comment] 2017-05-24 12:57
You can download Electron 1.7.1 from https://github.com/electron/electron/releases, it's still in beta stage, but I haven't noticed any issues so far.

**Comment by jarek-foksa** [comment] 2017-05-24 13:00
If I recall correctly, the old Chrome bug was triggered when there were two or more icons with the same name.

**Comment by sandor** [comment] 2017-05-24 13:05
thanks! using 1.7.1 solves the problem with the icons...

**Comment by sandor** [comment] 2017-05-24 13:16
sorry, unrelated question: seeng my screenshots above – how would I align the first button group left the second group in the middle and the third group on the right of my header using your x-box ?

**Comment by jarek-foksa** [comment] 2017-05-24 13:23
It's hard to say by looking at the code you pasted as you seem to be using some grid system. I would try applying `justify-content: center;` and `align-items: center;` on the `<x-box>` and/or other containers.

**Comment by sandor** [comment] 2017-05-24 13:41
awesome! thanks... justify-content: space-between; was the answer :-)

**Comment by jarek-foksa** [comment] 2017-06-11 14:07
I have updated the minimal Electron version required by Xel in the docs, so we can close this now.

**Closed by jarek-foksa** 2017-06-11 14:07 UTC
