### ISSUE TITLE
 x-menu Quick click will cause the page card to die

### ISSUE THREAD

**Issue by u10k** [jarek-foksa/xel#111] opened 2022-07-13 11:34 UTC
Bug Type: **`Component`**

## Environment

- xel Version: `0.16.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4336.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `x-menu`

### Reproduction Link

[Docs](https://xel-toolkit.org/elements/x-menu)

### Steps to reproduce

Right -click quickly

![image](https://user-images.githubusercontent.com/22042799/178724392-543a41d8-640c-411d-bd32-9201942731a4.png)

**Comment by u10k** [comment] 2022-07-14 01:04
> Can you reproduce this bug with the latest version of Chrome? You seem to be using Chrome 89 which is very old.

I found nothing to do with chrome version,  Affected by [x-contextmenu] 

`html
<x-menu id="x-menu">
   <x-menuitem>copy</x-menuitem>
</x-menu>
`
` js
document.body).addEventListener('contextmenu', (e) => {
            e.preventDefault();
            const elMenu = document.getElementById('x-menu');
            elMenu.openAtPoint(e.clientX, e.clientY);
 });
`
if i remove x-contextmenu, is good

**Comment by jarek-foksa** [comment] 2022-07-14 06:53
Please report this bug on https://bugs.chromium.org/p/chromium/, I can't do it as I'm unable to reproduce the crash. In the Chromium bug report you should include the 16 digit crash ID as shown on chrome://crashes

**Comment by u10k** [comment] 2022-07-14 09:06
> Please report this bug on https://bugs.chromium.org/p/chromium/, I can't do it as I'm unable to reproduce the crash. In the Chromium bug report you should include the 16 digit crash ID as shown on chrome://crashes

you can run this [https://github.com/u10k/xelMenu](https://github.com/u10k/xelMenu)

**Comment by jarek-foksa** [comment] 2022-07-14 11:23
Please provide unobfuscated test case.

**Comment by u10k** [comment] 2022-07-16 04:24
> Please provide unobfuscated test case.


[demo](https://u10k.github.io/xelMenu/)
[video](https://cloud.51peiq.com/client%2Fdemo%2FxelMenu.mp4)

<video id="video" controls="" preload="none" poster="封面">
      <source id="mp4" src="[mp4格式视频](https://cloud.51peiq.com/client%2Fdemo%2FxelMenu.mp4)" type="video/mp4">
</video>

**Comment by jarek-foksa** [comment] 2022-07-16 08:37
Thanks, I managed to reproduce the bug and I fixed in Xel version 0.17.2.

**Closed by jarek-foksa** 2022-07-16 08:37 UTC
